package pagesOfYasasiiWeb;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import com.baseYasasiiWeb.PageFactoryInitYasasiiWeb;

public class bedCreation extends PageFactoryInitYasasiiWeb{

	private static final char B = 0;


	public bedCreation(WebDriver driver) {
		super(driver);

	}

	@FindBy(xpath = "//a[@class='nav-link navbar-brand menu']//div[@class='menu-toggle']")
	public WebElement Menutoggle;

	@FindBy(xpath = "//i[@class='ki ki-cog']")
	public WebElement mastericon;

	@FindBy(xpath = "//div[@class='link-value'][normalize-space()='Resource']")
	public WebElement resource; 

	@FindBy(xpath = "//div[normalize-space()='Resource Master']")
	public WebElement resourceMaster; 

	@FindBy(xpath = "//input[@id='resourcecategory']")
	public WebElement category; 

	@FindBy(xpath = "//input[@id='roomid']")
	public WebElement ROOMcategory;

	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-Deluxe-Deluxe Room']")
	public WebElement  deluxRoom;
	
	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-Ultra-Deluxe-Ultra-Deluxe Room']")
	public WebElement  ultradeluxRoom;

	@FindBy(xpath = "//div[@title='A1 Block-Ground floor-ER_Exclusive-Emergengy Room']")
	public WebElement  emrgncyRoom;

	@FindBy(xpath = "//i[@class='ki ki-pencil']")
	public WebElement Edit;

	@FindBy(xpath = "//input[@id='bedtype']")
	public WebElement BedType;

	@FindBy(xpath = "//input[@id='nursingstation']")
	public WebElement nurestation;

	@FindBy(xpath = "//input[@id='bedname']")
	public WebElement bedname;

	@FindBy(xpath = "//span[@class='icon-btn btn-dark-green inline']")
	public WebElement bedAdd;

	@FindBy(xpath = "//button[@id='resourcemasterupdate']")
	public WebElement update;

	@FindBy(xpath = "//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")
	public WebElement floor;


	@FindBy(xpath = "//div[@class='form-group zero-bottom ki-dropdown']//input[@id='roomid']")
	public WebElement RoomWard;





	public void ultradeluxe() throws InterruptedException {

		Thread.sleep(2000);
		Menutoggle.click();
		Thread.sleep(600);
		mastericon.click();
		Thread.sleep(600);
		JavascriptExecutor js= (JavascriptExecutor) driver;
		js.executeScript("arguments[0].scrollIntoView();", resource );
		Thread.sleep(600);
		resource.click();
		Thread.sleep(600);
		resourceMaster.click();
		Thread.sleep(2000);
		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();                                  
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();

		ROOMcategory.click();
		Thread.sleep(600);
//		driver.findElement(By.xpath("//li[normalize-space()='Deluxe Room']")).click();
//		
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ultra-Deluxe Room']")).click();
		Thread.sleep(600);
//		deluxRoom.click();
//		Thread.sleep(600);
		
		ultradeluxRoom.click();
		Thread.sleep(600);
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1000");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1001");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1002");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1003");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1004");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1005");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1006");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1007");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1008");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1009");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1010");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1011");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1012");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1013");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1014");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1015");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1016");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1017");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1018");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1019");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1020");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1021");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1022");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1023");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1024");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1025");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1026");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1027");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1028");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1029");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1030");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1031");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1032");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1033");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1034");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1035");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1036");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1037");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1038");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1039");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1040");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1041");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1042");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1043");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1044");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1045");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1046");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1047");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1048");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1049");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1050");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1051");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1052");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1053");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1054");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1055");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1056");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1057");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1058");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1059");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1060");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1061");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1062");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1063");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1064");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1065");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1066");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1067");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1068");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1069");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);

		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1070");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1071");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1072");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1073");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1074");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1075");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1076");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1077");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1078");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1079");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1080");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1081");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1082");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1083");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1084");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1085");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1086");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1087");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1088");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1089");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1090");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1091");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1092");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1093");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1094");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1095");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1096");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1097");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1098");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-1099");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(2000);
		
	}

	public void bed() throws InterruptedException {

		String  a="A6";
		char b=67;


		Thread.sleep(2000);
		Menutoggle.click();
		Thread.sleep(600);
		mastericon.click();
		Thread.sleep(600);
		JavascriptExecutor js= (JavascriptExecutor) driver;
		js.executeScript("arguments[0].scrollIntoView();", resource );
		Thread.sleep(600);
		resource.click();
		Thread.sleep(600);
		resourceMaster.click();
		Thread.sleep(2000);
		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();                                  
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//div[@class='form-group zero-bottom ki-dropdown']//input[@id='floorid']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();

		ROOMcategory.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ultra-Deluxe Room']")).click();
		Thread.sleep(600);
		ultradeluxRoom.click();
		Thread.sleep(600);
		
//		driver.findElement(By.xpath("//li[normalize-space()='Deluxe Room']")).click();
//		Thread.sleep(600);
//		deluxRoom.click();
//		Thread.sleep(600);
	
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"0");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"1");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"2");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"3");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"4");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"5");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"6");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		//nurestation.click();
		Thread.sleep(600);
		//driver.findElement(By.xpath("//li[normalize-space()='Ward Nure_Nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"7");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"8");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("ANS-"+a+"9");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		//	bedname.sendKeys("ANS-1040");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);  
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Transfer nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-1"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-2"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-3"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-4"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		nurestation.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-5"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-6"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-7"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-8"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-9"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("transfer-10"+a+"");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(4000);


		WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
		wait.until(ExpectedConditions.elementToBeClickable(category));
		Thread.sleep(2000);



		////////////////////Emergency beds


		category.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Bed']")).click();
		Thread.sleep(600);

		driver.findElement(By.xpath("//div[@class='form-group zero-bottom ki-dropdown']//input[@id='hospitalid']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='"+Site+"']")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("/html[1]/body[1]/app-root[1]/app-layout[1]/main[1]/app-resourcemaster[1]/div[1]/lib-searchbarlist[1]/div[1]/div[2]/form[1]/div[3]/div[1]/ki-select-control[1]/div[1]/input[1]")).click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='A1 Block']")).click();
		Thread.sleep(600);
		floor.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Ground floor']")).click();
		Thread.sleep(600);
		RoomWard.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergengy Room']")).click();
		Thread.sleep(600);
		emrgncyRoom.click();
		Thread.sleep(600);
		Edit.click();
		Thread.sleep(600);
		BedType.click();
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Normal']")).click();
		Thread.sleep(600);
		nurestation.click();	
		Thread.sleep(600);
		driver.findElement(By.xpath("//li[normalize-space()='Emergency NS']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"0");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"1");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"2");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"3");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"4");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"5");
		Thread.sleep(600);
		bedAdd.click();
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"6");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		//nurestation.click();
		Thread.sleep(600);
		//driver.findElement(By.xpath("//li[normalize-space()='Ward Nure_Nursing station']")).click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"7");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"8");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		bedname.sendKeys("EXE-"+a+"9");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		bedname.click();
		Thread.sleep(600);
		//	bedname.sendKeys("ANS-1040");
		Thread.sleep(600);
		bedAdd.click();
		Thread.sleep(600);
		update.click();
		Thread.sleep(2000);








	}


}
